spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-aop-lab5
    username: postgres
    password: Pass2020!

  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8080
